FROM node:22-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# nginx config will be provided by file in this image
COPY nginx.conf /etc/nginx/conf.d/default.conf

# expose http
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
