# Generated by Django 4.2.30 on 2026-04-18 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_group_teacher_user_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-month', '-paid_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher_user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.CharField(blank=True, help_text='Reason for absence (if applicable)', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional payment notes'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(help_text='Class date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(help_text='Group for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True, help_text='Was the student present?'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='Student attendance', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(help_text='Proficiency level', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text="Group name (e.g., 'English A1')", max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Assigned teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(help_text='Class time (e.g., 18:00)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount in local currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(help_text='Student who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text="Student's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Enrolled study group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, help_text="Student's last name", max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent/Guardian phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(help_text="Student's phone number", max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(help_text="Teacher's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, help_text="Teacher's last name", max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for contact', max_length=30),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['group', 'date'], name='core_attend_group_i_e90a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher'], name='core_group_teacher_d5f2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['level'], name='core_group_level_f88631_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'month'], name='core_paymen_student_14bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['month'], name='core_paymen_month_d3dfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='core_studen_group_i_dca0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user'], name='core_studen_user_id_9db982_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['first_name', 'last_name'], name='core_teache_first_n_c7b939_idx'),
        ),
    ]
