# Generated by Django 4.2.30 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discount_learningcenter_teachersalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Kelgan'), ('absent', 'Kelmagan'), ('late', 'Kechikkan'), ('excused', 'Uzrli')], default='present', help_text='Attendance status', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Foiz'), ('fixed', "So'm")], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', "To'langan"), ('pending', 'Kutilmoqda'), ('overdue', "Muddati o'tgan"), ('partial', 'Qisman')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('graduated', 'Bitirgan'), ('suspended', "To'xtatilgan"), ('dropped', 'Ketgan')], default='active', help_text='Enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('leave', "Ta'tilda"), ('terminated', "Ishdan bo'shatilgan")], default='active', help_text='Employment status', max_length=20),
        ),
    ]
