# Generated by Django 4.2.30 on 2026-05-18 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendance_status_alter_discount_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Group start date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date student enrolled'),
        ),
    ]
