# Generated by Django 4.2.30 on 2026-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_groupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='homework_note',
            field=models.CharField(blank=True, help_text='Homework note or teacher comment', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='homework_status',
            field=models.CharField(choices=[('not_checked', 'Tekshirilmagan'), ('done', 'Bajargan'), ('partial', 'Qisman'), ('not_done', 'Bajarmagan')], default='not_checked', help_text='Student homework completion status', max_length=20),
        ),
    ]
