# Generated by Django 4.2.30 on 2026-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('operator', 'Operator'), ('admin', 'Administrator')], help_text='User role in the system', max_length=20, null=True),
        ),
    ]
